"""
Sample perfume data for testing the recommendation system
"""

sample_perfumes = [
    {
        "name": "Acqua di Gio",
        "brand": "Giorgio Armani",
        "concentration": "EDT",
        "price": 85.0,
        "fragrance_family": "Aromatic",
        "intensity": "Moderate",
        "longevity_hours": 6,
        "projection": "Moderate",
        "sillage": "Moderate",
        "top_notes": "Bergamot,Lemon,Lime,Jasmine",
        "middle_notes": "Calone,Freesia,Hyacinth,Cyclamen,Rosemary",
        "base_notes": "White Musk,Cedar,Oakmoss,Amber",
        "seasonal_focus": "Summer",
        "gender_presentation": "Masculine",
        "allergens": "Citrus oils",
    },
    {
        "name": "Chanel No. 5",
        "brand": "Chanel",
        "concentration": "EDP",
        "price": 150.0,
        "fragrance_family": "Floral",
        "intensity": "Strong",
        "longevity_hours": 8,
        "projection": "Strong",
        "sillage": "Heavy",
        "top_notes": "Aldehydes,Ylang-Ylang,Neroli,Bergamot,Lemon",
        "middle_notes": "Iris,Jasmine,Rose,Orris Root,Lily of the Valley",
        "base_notes": "Civet,Amber,Sandalwood,Musk,Moss,Vetiver,Vanilla",
        "seasonal_focus": "All-year",
        "gender_presentation": "Feminine",
        "allergens": "Aldehydes",
    },
    {
        "name": "Sauvage",
        "brand": "Dior",
        "concentration": "EDT",
        "price": 95.0,
        "fragrance_family": "Aromatic",
        "intensity": "Strong",
        "longevity_hours": 7,
        "projection": "Strong",
        "sillage": "Heavy",
        "top_notes": "Calabrian Bergamot,Pepper",
        "middle_notes": "Sichuan Pepper,Lavender,Pink Pepper,Vetiver,Patchouli,Geranium,Elemi",
        "base_notes": "Ambroxan,Cedar,Labdanum",
        "seasonal_focus": "All-year",
        "gender_presentation": "Masculine",
        "allergens": "Ambroxan,Lavender",
    },
    {
        "name": "Light Blue",
        "brand": "Dolce & Gabbana",
        "concentration": "EDT",
        "price": 75.0,
        "fragrance_family": "Citrus",
        "intensity": "Light",
        "longevity_hours": 4,
        "projection": "Moderate",
        "sillage": "Light",
        "top_notes": "Sicilian Lemon,Apple,Cedar,Bellflower",
        "middle_notes": "Bamboo,Jasmine,White Rose",
        "base_notes": "Cedar,Amber,Musk",
        "seasonal_focus": "Summer",
        "gender_presentation": "Feminine",
        "allergens": "Citrus oils",
    },
    {
        "name": "Tom Ford Oud Wood",
        "brand": "Tom Ford",
        "concentration": "EDP",
        "price": 320.0,
        "fragrance_family": "Woody",
        "intensity": "Strong",
        "longevity_hours": 10,
        "projection": "Moderate",
        "sillage": "Moderate",
        "top_notes": "Agarwood,Rosewood,Cardamom",
        "middle_notes": "Sandalwood,Palissander Rosewood,Sichuan Pepper",
        "base_notes": "Vanilla,Amber",
        "seasonal_focus": "Winter",
        "gender_presentation": "Unisex",
        "allergens": None,
    },
    {
        "name": "Flowerbomb",
        "brand": "Viktor & Rolf",
        "concentration": "EDP",
        "price": 125.0,
        "fragrance_family": "Floral",
        "intensity": "Strong",
        "longevity_hours": 8,
        "projection": "Strong",
        "sillage": "Heavy",
        "top_notes": "Tea,Bergamot,Osmanthus",
        "middle_notes": "Sambac Jasmine,Orchid,Freesia,Rose",
        "base_notes": "Musk,Vanilla,Amber,Patchouli",
        "seasonal_focus": "All-year",
        "gender_presentation": "Feminine",
        "allergens": None,
    },
    {
        "name": "Bleu de Chanel",
        "brand": "Chanel",
        "concentration": "EDP",
        "price": 140.0,
        "fragrance_family": "Woody",
        "intensity": "Moderate",
        "longevity_hours": 8,
        "projection": "Moderate",
        "sillage": "Moderate",
        "top_notes": "Grapefruit,Lemon,Mint,Pink Pepper,Artemisia",
        "middle_notes": "Ginger,Nutmeg,Jasmine,Melon",
        "base_notes": "Incense,Amber,Cedar,Sandalwood,Patchouli,Labdanum",
        "seasonal_focus": "All-year",
        "gender_presentation": "Masculine",
        "allergens": "Citrus oils",
    },
    {
        "name": "Black Opium",
        "brand": "Yves Saint Laurent",
        "concentration": "EDP",
        "price": 110.0,
        "fragrance_family": "Oriental/Spicy",
        "intensity": "Strong",
        "longevity_hours": 9,
        "projection": "Strong",
        "sillage": "Heavy",
        "top_notes": "Pink Pepper,Orange Blossom,Pear",
        "middle_notes": "Coffee,Jasmine,Bitter Almond,Licorice",
        "base_notes": "Vanilla,Patchouli,Cedar,Cashmere Wood",
        "seasonal_focus": "Winter",
        "gender_presentation": "Feminine",
        "allergens": None,
    },
    {
        "name": "Aventus",
        "brand": "Creed",
        "concentration": "EDP",
        "price": 350.0,
        "fragrance_family": "Fruity",
        "intensity": "Strong",
        "longevity_hours": 8,
        "projection": "Strong",
        "sillage": "Heavy",
        "top_notes": "Blackcurrant,Italian Bergamot,French Apples,Pineapple",
        "middle_notes": "Pink Pepper,Birch,Patchouli,Moroccan Jasmine",
        "base_notes": "Indian Sandalwood,Oakmoss,Ambergris,Vanilla",
        "seasonal_focus": "All-year",
        "gender_presentation": "Masculine",
        "allergens": None,
    },
    {
        "name": "La Vie Est Belle",
        "brand": "Lancome",
        "concentration": "EDP",
        "price": 105.0,
        "fragrance_family": "Floral",
        "intensity": "Moderate",
        "longevity_hours": 7,
        "projection": "Moderate",
        "sillage": "Moderate",
        "top_notes": "Black Currant,Pear",
        "middle_notes": "Iris,Jasmine,Orange Blossom",
        "base_notes": "Tonka Bean,Vanilla,Praline,Patchouli",
        "seasonal_focus": "All-year",
        "gender_presentation": "Feminine",
        "allergens": None,
    },
]
