"""update user table

Revision ID: 01093ec50de1
Revises: c5b23461c31d
Create Date: 2025-09-12 13:36:32.814843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01093ec50de1'
down_revision: Union[str, None] = 'c5b23461c31d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_name', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('gender', sa.String(), nullable=True))
    op.add_column('users', sa.Column('age_group', sa.String(), nullable=True))
    op.add_column('users', sa.Column('country_grew_up', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('country_of_residence', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'country_of_residence')
    op.drop_column('users', 'country_grew_up')
    op.drop_column('users', 'age_group')
    op.drop_column('users', 'gender')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###
