"""add questionnaire table

Revision ID: 882728a37344
Revises: a1b7aba5a6be
Create Date: 2025-09-10 15:04:38.277692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '882728a37344'
down_revision: Union[str, None] = 'a1b7aba5a6be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questionnaires',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.String(), nullable=True),
    sa.Column('question_text', sa.String(), nullable=False),
    sa.Column('question_topic', sa.String(), nullable=True),
    sa.Column('multiple_choices', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('perfumes', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('recommendations', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('user_profiles', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'created_at')
    op.drop_column('recommendations', 'created_at')
    op.drop_column('perfumes', 'created_at')
    op.drop_table('questionnaires')
    # ### end Alembic commands ###
