"""update questionnaire table

Revision ID: c5b23461c31d
Revises: 36e6464594df
Create Date: 2025-09-12 09:27:42.814368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5b23461c31d'
down_revision: Union[str, None] = '36e6464594df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questionnaires', sa.Column('type', sa.String(), nullable=True))
    op.add_column('questionnaires', sa.Column('can_select_multiple', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questionnaires', 'can_select_multiple')
    op.drop_column('questionnaires', 'type')
    # ### end Alembic commands ###
